{% set name = "pymsbuild" %}
{% set version = "1.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pymsbuild-{{ version }}.tar.gz
  sha256: 6f0b28e0785b2cc9a969cbefa1a8a4b518cc7da27a859f56ce2e395fc1229a89

build:
  number: 0
  skip: true  # [not (win and py>=37)]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - packaging
  run:
    - python
    - packaging

test:
  imports:
    - pymsbuild
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/zooba/pymsbuild
  summary: The pymsbuild build backend.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
