{% set name = "pymsbuild" %}
{% set version = "0.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pymsbuild-{{ version }}.tar.gz
  sha256: 43d5946cac5918f466199a27d3074abdeae8923aea84d4f90fde538064d8ec31

build:
  number: 0
  skip: true  # [not (win and py>=37)]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - packaging
  run:
    - python
    - packaging

test:
  imports:
    - pymsbuild
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/zooba/pymsbuild
  summary: The pymsbuild build backend.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
