{% set name = "pymsbuild" %}
{% set version = "0.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pymsbuild-{{ version }}.tar.gz
  sha256: 64685ecddd735fdc2c1bf6783ae7999304fd41d553f28d7b6a4071766956cf90

build:
  number: 0
  skip: true  # [not (win and py>=37)]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - packaging
  run:
    - python
    - packaging

test:
  imports:
    - pymsbuild
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/zooba/pymsbuild
  summary: The pymsbuild build backend.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
