{% set name = "pymsbuild" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pymsbuild-{{ version }}.tar.gz
  sha256: 1e9d92414a8d444291974364d0bf50d72032f06b411db7126ded6dcfd66f3740

build:
  number: 0
  skip: true  # [not (win and py>=37)]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - packaging
  run:
    - python
    - packaging

test:
  imports:
    - pymsbuild
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/zooba/pymsbuild
  summary: The pymsbuild build backend.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
