{% set name = "pymsbuild" %}
{% set version = "1.1.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pymsbuild-{{ version }}.tar.gz
  sha256: 34fabd894448156a041457bd8e2fee2c1a3695846aa27a9b1e96fcdcf80b7aa1

build:
  number: 0
  skip: true  # [not (win and py>=37)]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - packaging
  run:
    - python
    - packaging

test:
  imports:
    - pymsbuild
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/zooba/pymsbuild
  summary: The pymsbuild build backend.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
