schema_version: 1

context:
  name: pymsbuild
  version: "1.2.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pymsbuild-${{ version }}.tar.gz
  sha256: 3062c8ae924e2a43abe254d78048457bf433e0375d8a671f02950515c42a4347

build:
  number: 0
  skip: not (win and match(python, ">=3.7"))

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
  host:
    - python
    - pip
    - packaging
  run:
    - python
    - packaging

tests:
  - python:
      imports:
        - pymsbuild
  - requirements:
      run:
        - pip
    script:
      - pip check

about:
  summary: The pymsbuild build backend.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/zooba/pymsbuild

extra:
  recipe-maintainers:
    - xhochy
