schema_version: 1

context:
  name: pymsbuild
  version: 1.1.7

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pymsbuild-${{ version }}.tar.gz
  sha256: 0a0f19507a212930e9d6d8c1a504929c9ae1c517b4ab887c73a31c91b08833ba

build:
  number: 0
  skip: not (win and match(python, ">=3.7"))

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
  host:
    - python
    - pip
    - packaging
  run:
    - python
    - packaging

tests:
  - python:
      imports:
        - pymsbuild
  - requirements:
      run:
        - pip
    script:
      - pip check

about:
  summary: The pymsbuild build backend.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/zooba/pymsbuild

extra:
  recipe-maintainers:
    - xhochy
